name: Super-Linter

on: 
  push:
    branches:
      - main # Specify the branch where the workflow should trigger

jobs:
  super-lint:
    name: Lint code base
    runs-on: ubuntu-latest
    steps:
      - name: 23f3001374@ds.study.iitm.ac.in
        run: echo "Hello, world!"    
      - name: Run Super-Linter
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main # Update if your default branch is different
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
